name: medium_uz
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  flutter_screenutil: ^5.8.4
  flutter_bloc: ^8.1.3
  sqflite: ^2.3.0
  dio: ^5.3.2
  image_picker: ^1.0.1
  zoom_tap_animation: ^1.1.0
  shared_preferences: ^2.2.0
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  pinput: ^3.0.0
  mask_text_input_formatter: ^2.5.0
  keyboard_dismisser: ^3.0.0
  lottie: ^2.6.0
  url_launcher: ^6.1.12
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/translations/
    - assets/lottie/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Regular.ttf
        - asset: assets/fonts/Sora-Light.ttf
        - asset: assets/fonts/Sora-Medium.ttf
        - asset: assets/fonts/Sora-SemiBold.ttf
        - asset: assets/fonts/Sora-Bold.ttf
        - asset: assets/fonts/Sora-ExtraBold.ttf
          style: italic